on:
  workflow_dispatch:
    inputs:
      name-to-greet:
        description: 'Name of whom to greet'
        required: true
        default: 'World!'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: carlosmmatos/hello-world-javascript-action@v0.0.2
        with:
          who-to-greet: ${{ inputs.name-to-greet }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
